### PR TITLE
Add query string params to haproxy.http_req

### PR DESCRIPTION
**Pull request by perangel**
Also added:
    * http_version
    * http_method

### CODE REVIEW

**Comment by perangel** [comment]
@pmbauer Do you think it's a risk to capture the query string params in our logs?

**Comment by earldouglas** [comment]
I don't know the risk level of this given our current APIs, but ideally it *shouldn't* be a risk because sensitive data doesn't belong in URLs.

**Comment by pmbauer** [comment]
I'd just concurrently typed pretty much what @earldouglas said.
To the extent that we are already capturing the full query string, this commit just orgnaizes the current http_req field a little better
https://esp.udacity.com/_plugin/kibana/#/doc/logstash-*/logstash-2016.09.28/syslogjson/?id=AVdyX3C8TVq8hH-c12wq

However I do know 3rd party services like segment call into data services passing in api tokens in their request string.

**Comment by perangel** [comment]
Actually, I think I was looking at the wrong set of logs in kibana when I though that the QS params were not on the URL. AFAIK they are *are* captured correctly.

**Pull request closed without merging**
