### PR TITLE
HAProxy websocket enabled backends using service tags

### PR DESCRIPTION
**Pull request by perangel**
First pass at ws-enabled backends using service tags

### CODE REVIEW

**Comment by pmbauer** [comment]
so 'websockets' tag implies public
If a service has the following tags 'websockets,public' we'll get multiple backends?

Is there some way to conditionally put 'no option httpclose' in the existing backend section dependent on presence of 'websockets' or (maybe preferable 'sticky') in the tag list?

**Comment by perangel** [comment]
Correct, a ws-configured backend is generated that only handles traffic for websocket connections (e.g. Connection: Upgrade). There might be a way to optionally put `no option httpclose` but we can't flip that on a per request and by default I think we want httpclose enabled on backends.

Also, if there is additional ws-related configs that we would put in place, then we'd put them in the <host>_backend_ws block.

The idea of multiple backends seems very un-DRY but it seems to be a common pattern I'm seeing with people documenting websocket-enabled setups. It also lets you track stats separately for the different types.

**Comment by perangel** [comment]
http://blog.haproxy.com/2012/11/07/websockets-load-balancing-with-haproxy/

**Comment by pmbauer** [comment]
Okay that last point "track stats separately" based on a backend name pattern makes sense.  All the other concerns could be addressed by a more DRY <if ws>do this <endif> section in the existing backend.

As long as it's well understood that tagging a service with 'websockets' is effectively a super-set of public.

**Pull request merged**
