### PR TITLE
rsyslog,haproxy: increase max log size to 64K

### PR DESCRIPTION
**Pull request by pmbauer**
1. 64K should be enough for anyone
2. 64K is the largest size supported for haproxy

Our haproxy logs are currently getting truncated at 1024, which results
in truncated JSON and 25-30K unparsed request messages an hour.

### CODE REVIEW

**Comment by pmbauer** [comment]
tested in berlioz-paul
will move to berlioz-dev first after LGTM and squash-to-master

**Comment by pmbauer** [comment]
Deployment concerns:
deploy rsyslog changes first, restarting rsyslog results in haproxy taking awhile to recognize its socket connection to rsyslog is stale.  Since haproxy has to be restarted cluster-wide anyway, just do that immediately afterwards to minimize log gaps.

**Comment by pmbauer** [comment]
```
make update CMD=ansible_playbook_run ANSIBLE_EXARGS='--tags rsyslog'
make update_proxy
```

**Comment by perangel** [comment]
lgtm

**Pull request merged**
